### ISSUE TITLE
Upgrade from  1.6.26~ynh1 fails

### ISSUE THREAD

**Issue by autra** [YunoHost-Apps/grav_ynh#54]
### Describe the bug

Upgrade from 1.6.26\~ynh1 to current version (1.7.3\~ynh1) fails. Here is the logs https://paste.yunohost.org/raw/honudinaju

*A clear and concise description of what the bug is.*

### Context

- Hardware: Other ARM board 
- YunoHost version:
```
sudo yunohost --version
yunohost:
  repo: stable
  version: 4.1.7.1
yunohost-admin:
  repo: stable
  version: 4.1.4
moulinette:
  repo: stable
  version: 4.1.4
ssowat:
  repo: stable
  version: 4.1.3
```
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen -> all of them ;-)
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: none that is relevant here
- Using stable version
- current package version: 1.6.26~ynh1

### Steps to reproduce

- be on version 1.6.26~ynh1
- execute:
```sh
		sudo yunohost app upgrade grav
```

### Expected behavior

The update completes successfully.

## actual behavior

The update fails and the app is rollbacked (and that rollback succeeds, which is not always the case, so kudos to the maintainer \o/ )

### Logs

https://paste.yunohost.org/raw/honudinaju

Relevant part (probably) 

```
2021-02-06 16:01:48,510: DEBUG - One of the packages require Grav >=1.7.4. Please update Grav to the latest release.
2021-02-06 16:01:48,510: DEBUG - Error: An error occurred while trying to install the packages
```
