### ISSUE TITLE
Unable to install Grav on Yunohost

### ISSUE THREAD

**Issue by alexandremottier** [YunoHost-Apps/grav_ynh#66]
# From the admin WebGUI

When I'm trying to install Grav on the web interface nothing happens (can't access to the parameters webpage).

# From the CLI

When I'm trying to install from the CLI, got an error :

`Error: Argument 'admin' is required`

# Configuration

* Raspbian 10 up-to-date
* YunoHost 4.1.7.4

```
root@yh2:~# yunohost tools versions
yunohost: 
  repo: stable
  version: 4.1.7.4
yunohost-admin: 
  repo: stable
  version: 4.1.4
moulinette: 
  repo: stable
  version: 4.1.4
ssowat: 
  repo: stable
  version: 4.1.3
```
# Result of the 'apt upgrade' command

```
root@yh2:~# apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@yh2:~#
```
